RF.Modules.TestFlightAppointment/Controllers/TestFlightGridController.cs
using DotNetNuke.Framework;
using DotNetNuke.Framework.JavaScriptLibraries;
using DotNetNuke.Web.Mvc.Framework.ActionFilters;
using DotNetNuke.Web.Mvc.Framework.Controllers;
using RF.Modules.TestFlightAppointment.Models;
using RF.Modules.TestFlightAppointment.Services;
using RF.Modules.TestFlightAppointment.Util;
using System;
using System.Web.Mvc;

namespace RF.Modules.TestFlightAppointment.Controllers
{
    [DnnHandleError]
    public class TestFlightGridController : DnnController
    {
        private ITestFlightBookingManager BookingManager { get; }

        public TestFlightGridController(
            ITestFlightBookingManager bookingManager
            )
        {
            BookingManager = bookingManager
                ?? throw new ArgumentNullException(nameof(bookingManager));
        }
        private static void InitPopup()
        {
            DotNetNuke.Framework.JavaScriptLibraries.JavaScript.RequestRegistration(CommonJs.jQuery);
            DotNetNuke.Framework.JavaScriptLibraries.JavaScript.RequestRegistration(CommonJs.DnnPlugins);
            ServicesFramework.Instance.RequestAjaxScriptSupport();
        }

        [HttpGet]
        public ActionResult Index(int? year, int? week)
        {
            var weekOfYear = year.HasValue && week.HasValue
                ? new WeekOfYear(year.Value, week.Value)
                : new WeekOfYear(DateTime.UtcNow);

            var utcNow = DateTime.UtcNow;
            var bookings = BookingManager.FindBookingsByDate(weekOfYear.FirstDay, weekOfYear.LastDay, false);
            ViewBag.Bookings = bookings;
            ViewBag.WeekOfYear = weekOfYear;

            return View();
        }

        [HttpGet]
        public ActionResult Create(DateTime? departureAt)
        {
            InitPopup();

            var model = new CreateBookingParameters()
            {
                DepartureAt = departureAt ?? DateTime.UtcNow,
            };

            ViewBag.Plans = BookingManager.FindFlightPlans(
                User.IsAdmin
                );
            ViewBag.PassengerTypes = new SelectList(new[]
            {
                new SelectListItem() { Text = "-- select --", Value = null, Selected = true },
                new SelectListItem() { Text = "Passenger", Value = "passenger", },
                new SelectListItem() { Text = "Pilot", Value = "pilot" },
                new SelectListItem() { Text = "Engineer", Value = "engineer" },
            }, nameof(SelectListItem.Value), nameof(SelectListItem.Text));

            return PartialView("Create", model);
        }

        [HttpGet]
        public ActionResult Detail(int bookingID)
        {
            InitPopup();

            var booking = BookingManager.FindBookingByID(bookingID);
            return View(booking);
        }
    }
}

RF.Modules.TestFlightAppointment/Views/TestFlightGrid/Create.cshtml
@inherits DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<RF.Modules.TestFlightAppointment.Models.CreateBookingParameters>

@using System.Web.Mvc;

@using DotNetNuke.Web.Client.ClientResourceManagement
@using DotNetNuke.Framework.JavaScriptLibraries

@using RF.Modules.TestFlightAppointment.Models;

@{
    ClientResourceManager.RegisterScript(Dnn.DnnPage, "~/DesktopModules/MVC/RF.Modules.TestFlightAppointment/Scripts/BookingGrid.js");

    var plans = ViewBag.Plans as TestFlightPlan[]
        ?? new RF.Modules.TestFlightAppointment.Models.TestFlightPlan[0];
    var planOptions = new SelectList(plans, "FlightPlanID", "Name");
    var passengerTypeOptions = ViewBag.PassengerTypes as SelectList;
    var submitID = String.Format("submit-{0}", Guid.NewGuid());
    var errorID = String.Format("error-{0}", Guid.NewGuid());
    var formID = String.Format("form-{0}", Guid.NewGuid());
    var passengersFormID = String.Format("passengers-{0}", Guid.NewGuid());
}

<h1>Create a booking</h1>

@using System.Collections.Generic
@using DotNetNuke.Web.Mvc.Helpers

<div id="Item-@Dnn.ModuleContext.ModuleId">
    <div class="dnnForm dnnEditBasicSettings" id="@formID">
        <p id="@errorID"></p>
        <fieldset>
            <div class="dnnFormItem">
                <div><label for="departureAt">Departure at</label></div>
                <p>@Model.DepartureAt</p>
                @Html.HiddenFor(m => m.DepartureAt)
            </div>
            <div class="dnnFormItem">
                <div><label for="planID">Flight plan</label></div>
                @Html.DropDownListFor(m => m.PlanID, planOptions)
            </div>
        </fieldset>
    </div>

    <div class="dnnForm" id="@passengersFormID">
        <h2>Passengers</h2>
        @for (var i = 0; i < 5; i++)
        {
            <fieldset class="dnnInlineForm" data-role="tf-passenger-row">
                <div class="dnnFormItem">
                    <div><label for="planID">Role</label></div>
                    @Html.DropDownList("PassengerRole", passengerTypeOptions)
                    @Html.ValidationMessage("PassengerRole", "This field is mandatory.")
                </div>
                <div class="dnnFormItem">
                    <div><label for="departureAt">Name</label></div>
                    @Html.TextBox("PassengerName")
                    @Html.ValidationMessage("PassengerName", "This field is mandatory.")
                </div>
                <div class="dnnFormItem">
                    <div><label for="departureAt">License</label></div>
                    @Html.TextBox("PilotLicense")
                    @Html.ValidationMessage("PassengerName", "This field is mandatory for pilots.")
                </div>
            </fieldset>

        }
    </div>

    <button type="button" id="@submitID" class="dnnPrimaryAction">Book Test Flight</button>
    <a id="cancelEdit" href="#" class="dnnSecondaryAction">Cancel</a>
</div>

<script type="text/javascript">
    (function ($, Sys) {
        $(function () {
            $('#cancelEdit').click(function () { dnnModal.closePopUp(false); });

            var passengerGrid = new BookingGridForm('#@passengersFormID');

            $('#@submitID').click(function () {
                if (!passengerGrid.validate())
                    return;

                var planID = $('#@formID')
                    .find('[name="PlanID"]')
                    .val();
                var data = {
                    planID,
                    departureAt: '@Model.DepartureAt.ToString("s")'
                };

                var proxy = new TestFlightBookingProxy(
                    '@Dnn.ActiveModule.ModuleID',
                    'TestFlightBooking'
                );
                passengerGrid.submit(
                    proxy,
                    data,
                    function (success, response) {
                        if (success) {
                            dnnModal.closePopUp(true);

                        } else {
                            $('#@errorID').html(response);

                        }
                    });
            });
        });




    }(jQuery, window.Sys));
</script>

RF.Modules.TestFlightAppointment/Views/TestFlightGrid/Detail.cshtml
@inherits DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<BookingData>

@using DotNetNuke.Web.Client.ClientResourceManagement
@using DotNetNuke.Framework.JavaScriptLibraries

@using RF.Modules.TestFlightAppointment.Services;

@{
    ClientResourceManager.RegisterScript(Dnn.DnnPage, "~/DesktopModules/MVC/RF.Modules.TestFlightAppointment/Scripts/BookingGrid.js");

    ViewBag.Title = "Test flight Booking Detail";

    var cancelBookingID = String.Format("cancel-{0}", Guid.NewGuid());
    var errorID = String.Format("error-{0}", Guid.NewGuid());
}

@if (Model == null)
{
    <p>This is an invalid booking.</p>
}
else
{

    <h2>Flight schedule</h2>
    <hr />
    <h3>Departure at @Model.Booking.DepartureAt.ToString("yyyy-MM-dd HH:mm:ss") (UTC)</h3>
    <h3>Duration: @Model.Booking.Duration hour(s)</h3>

    <h3>Flight plan</h3>
    <hr />
    <p class="tf-plan-name">@Model.Plan.Name</p>
    <p class="tf-plan-description">@Model.Plan.Description</p>

    <h3>Passengers</h3>
    <hr />
    <table class="tf-participants">
        <thead>
            <tr>
                <th>Passenger</th>
                <th>Role</th>
                <th>Licence</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var participant in Model.Participants)
            {
                <tr>
                    <td>@participant.PassengerName</td>
                    <td>@participant.Role</td>
                    <td>@participant.PilotLicense</td>
                </tr>
            }
        </tbody>
    </table>

    <p id="@errorID"></p>
    <button type="button" id="@cancelBookingID" class="dnnDeleteAction">Cancel Test Flight</button>
}
<a id="cancelEdit" href="#" class="dnnSecondaryAction">Close</a>

<script type="text/javascript">
    (function ($, Sys) {
        $(function () {
            $('#cancelEdit').click(function () { dnnModal.closePopUp(false); });

            $('#@cancelBookingID').click(function () {

                var dialog = new BookingDialog(
                    'Confirm',
                    'Do you really want to cancel this booking?'
                );
                dialog
                    .option('cancel', { caption: 'Cancel' })
                    .option('confirm', { caption: 'Confirm', type: 'Delete' })
                    .show(function (choice) {
                        switch (choice) {
                            case 'cancel':
                                dnnModal.closePopUp(true);
                                break;

                            case 'confirm':
                                var proxy = new TestFlightBookingProxy(
                                    '@Dnn.ActiveModule.ModuleID',
                                    'TestFlightBooking'
                                );
                                proxy.cancel(
                                        @Model.Booking.BookingID,
                                    function (success, response) {
                                        if (success) {
                                            dnnModal.closePopUp(true);

                                        } else {
                                            $('#@errorID').html(response);

                                        }
                                    });
                                break;
                        }
                    })
            });
        });



    }(jQuery, window.Sys));
</script>

RF.Modules.TestFlightAppointment/Views/TestFlightGrid/Index.cshtml
@inherits DotNetNuke.Web.Mvc.Framework.DnnWebViewPage

@using DotNetNuke.Web.Client.ClientResourceManagement
@using DotNetNuke.Framework.JavaScriptLibraries
@using RF.Modules.TestFlightAppointment.Services
@using RF.Modules.TestFlightAppointment.Models;
@using RF.Modules.TestFlightAppointment.Util;
@using System.Linq;

@{
    ClientResourceManager.RegisterScript(Dnn.DnnPage, "~/DesktopModules/MVC/RF.Modules.TestFlightAppointment/Scripts/BookingGrid.js");

    var utcNow = DateTime.UtcNow;
    var weekOfYear = (WeekOfYear)ViewBag.WeekOfYear;
    var startDay = weekOfYear.FirstDay;
    var localNow = DateTime.Now;

    var bookings = ViewBag.Bookings as BookingData[]
        ?? new BookingData[] { };
    var prevline = new BookingData[7];
    var thisWeek = new WeekOfYear(utcNow);
    var nextWeek = weekOfYear.AddWeeks(1);
    var prevWeek = weekOfYear.AddWeeks(-1);
}

<p>
    Please remember, the dates in the grid are in UTC time as our flight operations
    uses UTC time.
</p>

<div class="tf-header">
    <h2>@(weekOfYear.FirstDay.ToShortDateString()) - @(weekOfYear.LastDay.ToShortDateString())</h2>
    <hr />
</div>

<table class="tf-booking-grid">
    <thead>
        <tr>
            <th></th>
            @for (var i = 0; i < 7; i++)
            {
                var day = startDay.AddDays(i);
                <th>
                    @day.ToString("dddd")<br />
                    (@day.ToShortDateString())
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < 8; i++)
        {
            var offset = TimeSpan.FromHours(i * 3);
            var time = utcNow.Date + offset;

            <tr>
                <th>
                    LOCAL: @time.ToLocalTime().ToString("HH:mm")<br />
                    (UTC: @time.ToString("HH:mm"))
                </th>
                @for (var d = 0; d < 7; d++)
                {
                    var cellDay = startDay.AddDays(d);
                    var cellTime = cellDay.AddHours(i * 3);
                    var isPast = cellTime < utcNow;
                    var isLocked = cellTime < utcNow.AddHours(12);
                    var booking = bookings.FirstOrDefault(b => b.IsBookedAt(cellTime, 3));
                    var isBooked = booking != null;
                    var isFree = !isPast && !isLocked && !isBooked;
                    var displayUserName = booking != null
                        && booking.User != null
                        && Dnn.User.IsAdmin;
                    var cellCssClass = isPast || isLocked
                        ? "not-available"
                        : (isBooked ? "booked" : "free");
                    var isRepeated = booking != null && prevline[d] == booking;
                    prevline[d] = booking;
                    // TODO: take in account the time starts the day before this
                    var rowspan = booking == null ? 1 : (int)Math.Ceiling(booking.Duration / 3d);

                    if (!isRepeated)
                    {
                        <td class="@cellCssClass" rowspan="@rowspan">


                            @if (booking != null)
                            {
                                <a href="@Url.Action("Detail", "TestFlightGrid", new {ctl = "Detail", bookingID = booking.BookingID })">
                                    <div class="box">
                                        <span>
                                            <strong>@(booking.Plan.Name)</strong><br />
                                            @if (displayUserName)
                                            {
                                                @(booking.User.DisplayName)
                                            }
                                        </span>
                                    </div>
                                </a>
                            }
                            else if (isFree)
                            {
                                <a href="@Url.Action("Create", "TestFlightGrid", new {ctl = "Create", departureAt = cellTime })">
                                    <div class="box">
                                        <span class="autohide">Create booking</span>
                                    </div>
                                </a>
                            }


                        </td>
                    }

                }
            </tr>
        }
    </tbody>
</table>

<div class="tf-nav-control">
    <a href="@Url.Action("Index")?year=@(nextWeek.Year)&week=@(nextWeek.Week)" class="dnnSecondaryAction tf-right">Next week</a>
    <a href="@Url.Action("Index")?year=@(thisWeek.Year)&week=@(thisWeek.Week)" class="dnnSecondaryAction tf-center">This week</a>
    <a href="@Url.Action("Index")?year=@(prevWeek.Year)&week=@(prevWeek.Week)" class="dnnSecondaryAction tf-left">Previuos week</a>
</div>

<script type="text/javascript">
    /*globals jQuery, window, Sys */
    (function($, Sys) {
        var sf = $.ServicesFramework('@Dnn.ActiveModule.ModuleID');
        // var serviceUrl = sf.getServiceRoot('TestFlightAppointmentApi');
        var serviceUrl = sf.getServiceRoot('TestFlightBooking');

        console.log("!!! WRN !!!" + @Dnn.ActiveModule.ModuleID);
        console.log("!!! WRN !!!" + serviceUrl);

    }(jQuery, window.Sys));
</script>